### ISSUE TITLE
Error when trying to log in RCON

### ISSUE THREAD

**Issue by Swarkin** [Owen-Cochell/mctools#10]
```
me@linuxmint:~$ mcli srv.kackadu.de:25567 rcon RCONPass
+========================================================================+
# Starting TCP connection to RCON server @ srv.kackadu.de:25567 ...
# Started TCP connection to RCON server @ srv.kackadu.de:25567!
# Authenticating with RCON server ...
Traceback (most recent call last):
  File "/home/me/.local/bin/mcli", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/mctools/__main__.py", line 389, in main
    val = rcon.authenticate(args.password)
  File "/home/me/.local/lib/python3.10/site-packages/mctools/mclient.py", line 396, in authenticate
    return self.login(password)
  File "/home/me/.local/lib/python3.10/site-packages/mctools/mclient.py", line 370, in login
    pack = self.raw_send(self.proto.LOGIN, password)
  File "/home/me/.local/lib/python3.10/site-packages/mctools/mclient.py", line 297, in raw_send
    pack = self.proto.read()
  File "/home/me/.local/lib/python3.10/site-packages/mctools/protocol.py", line 259, in read
    pack = RCONPacket.from_bytes(byts)
  File "/home/me/.local/lib/python3.10/site-packages/mctools/packet.py", line 87, in from_bytes
    reqid, reqtype, payload = RCONEncoder.decode(byts)
  File "/home/me/.local/lib/python3.10/site-packages/mctools/encoding.py", line 96, in decode
    reqid, reqtype = struct.unpack("<ii", byts[:8])
struct.error: unpack requires a buffer of 8 bytes
```
Am I using it wrong, or is it broken?
It's a 1.19.2 Paper server.

**Comment by Swarkin** [comment]
I fixed the previous err, but now get `OSError: [Errno 113] No route to host`

**Comment by Owen-Cochell** [comment]
Hello! Thank you for reporting this.

So in this case it appears that there are other factors at play that would cause this error, such as misconfiguration or network errors. I doubt the issue is related to mctools, but just to be sure we can walk through some common debugging questions, and hopefully we can get it working. First off, is RCON enabled in the server you are using? Also, is it possible to connect to your minecraft server in game? Finally, what version of mctools are you using?

By the way, what did you do to get the original error fixed? That problem does appear to be an issue with mctools, as it seems that the decoder did not do something correctly. I would be very interested to know more about how this error happened and how you fixed it.

Thanks!

**Comment by Swarkin** [comment]
I'm not sure what I did in the first error, I don't have that code available anymore, but I do know that I accidentally provided the wrong port.

However, I've found a fix to `OSError: [Errno 113] No route to host`:
I had to supply the local IP instead of the global one, as I didn't have that port forwarded.
Not sure why it worked with my public IP and the `QUERYClient` tho, as the IP it was configured to _isn't_ forwarded either..

Well, at least it works now after some experimenting!
