### ISSUE TITLE
add timeout

### ISSUE THREAD

**Issue by Tarbian** [Owen-Cochell/mctools#11]
Add timeout parameter to `rcon.login(pass)`, `query.get_full_stats()` , `query.get_basic_stats()`
When the server is down, a lot of time is wasted.

**Comment by Owen-Cochell** [comment]
Hello!

Thanks for the idea, I really appreciate it. I'll get this implemented by the end of the day.

Thanks

**Comment by Owen-Cochell** [comment]
After looking into this some more, I think a solution already exists that does not require additions to any function definitions. You can set the timeout value on any client using the `set_timeout()` method. As of now it fails if the client is not started, but later today I will be pushing a change that allows the timeout to be set before the client is started, allowing for the timeout to be set for all of these operations ahead of time. For example, if you want to set a timeout for login but a different timeout for RCON commands:

```python
# Set the set the timeout to 10 seconds for login:

rcon.timeout(10)

# Do login operation:

rcon.login(pass)

# Now, set a new timeout for command operations, 60 seconds (assume login succeeded)

rcon.set_timeout(60)

# From this point on, timeout will be 60 seconds for all operations:

rcon.command("broadcast Hello RCON!")
```

This will make the timeout for the login operation 10 seconds, and after we have logged in we set the timeout to something more forgiving, such as 60 seconds. You can also specify a custom timeout when creating your client:

```python
rcon = RCONClient(host, timeout=5)  # Sets the timeout to 5 seconds
```

Both operations above work for all clients, not just RCONClient! I believe this solves your problem, meaning that I believe there is no need to add more functionality after the `set_timeout()` bug is fixed. However, if you believe that it would be beneficial to include a timeout parameter as you suggested, then we can talk about it! You might have insight that I lack. Otherwise, we can close this issue if you consider your problem solved.

Thanks again!

**Comment by Towux** [comment]
help pls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Towa\AppData\Local\Programs\Python\Python39\lib\site-packages\mctools\mclient.py", line 709, in get_full_stats
    chall = self.get_challenge().chall
  File "C:\Users\Towa\AppData\Local\Programs\Python\Python39\lib\site-packages\mctools\mclient.py", line 645, in get_challenge
    pack = self.raw_send(9, None, "chall")
  File "C:\Users\Towa\AppData\Local\Programs\Python\Python39\lib\site-packages\mctools\mclient.py", line 625, in raw_send
    self.proto.send(QUERYPacket(reqtype, self.reqid, chall, packet_type))
  File "C:\Users\Towa\AppData\Local\Programs\Python\Python39\lib\site-packages\mctools\protocol.py", line 350, in send
    self.write_udp(byts, self.host, self.port)
  File "C:\Users\Towa\AppData\Local\Programs\Python\Python39\lib\site-packages\mctools\protocol.py", line 128, in write_udp
    self.sock.sendto(byts, (host, port))
socket.gaierror: [Errno 11001] getaddrinfo failed

code:
from mctools import QUERYClient
query = QUERYClient('ip:port')
stats = query.get_full_stats()
