### ISSUE TITLE
RCONClient.command hangs indefinitely when no data is received from the server

### ISSUE THREAD

**Issue by alexitx** [Owen-Cochell/mctools#4]
Sending a command and waiting for the result might hang indefinitely if there's no data received even after the server is shut down.

Relevant part according to the best of my troubleshooting: https://github.com/Owen-Cochell/mctools/blob/6f3709430d8ab84b6d9d5a362e3fd545f30d0aa2/mctools/protocol.py#L77

If a command send fails with reasonable timeout set, followed by another attempt, but this time the server is resumed (i.e. stoppped lagging, connection came back up after packet loss, etc.) within the given timeout, the server (seems?) to send the response back to the first request. The second `rcon.command(...)` sends the data, but doesn't receive anything and waits forever unless interrupted by ^C for example.

Example snippet to reproduce:

```python
import socket
from mctools.mclient import RCONClient

with RCONClient('127.0.0.1', timeout=5) as rcon:
    rcon.login('password')
    input('Suspend the server and press enter') # Suspend the server process
    try:
        result = rcon.command('help') # Let one timeout expire
    except socket.timeout:
        print('Resume the server') # Reusme the server after the first timeout (5+ seconds)
        result = rcon.command('help') # Hangs indefinitely
    print(result)
```

**Comment by Owen-Cochell** [comment]
Thank you for posting an issue, this is definitely a problem with mctools!

I have done some testing on my end with the example code and situation that you provided, and I have found that once the connection has been closed(i.e, server process is stopped), the socket will return an empty byte string when 'recv()' is called. Because RCONProtocol is designed to read bytes until the number of the bytes received matches the number bytes excepted, the code gets stuck in an endless loop of reading nothing. I'm sure you can see how this can be a problem!

It was my understanding that an exception would be raised when the peer closes the connection, which is what I would expect from the server closing. Instead, it appears that RCON does not close the socket, but instead denotes that it is done sending information. The TCP protocol will keep the connection open until both sides report that they are done writing, which leads to mctools endlessly reading nothing.

Point is, this seems to be an issue with mctools not properly understanding network etiquette, not necessarily an issue with timeouts. I tested this on my Linux machine, and I will later test it on Windows to ensure the functionality is the same. I think the solution here is to have mctools recognise an empty byte string, and shut itself down, as the server we are trying to talk to is down.

Thanks for finding this and pointing it out! This is a pretty huge oversight, and I will be pushing out a solution in the coming days. If I missed anything or misunderstood the question, then please let me know and we can clarify. I'll mark this issue as resolved once I have pushed a fix and have properly tested it. If that doesn't fix the problem on your end, then we will figure something else out.

Thanks!

**Comment by alexitx** [comment]
Thank you for the fast response on this issue.

I'm not very experienced when it comes to working with sockets, so some of the terminologies I'm using might be completely incorrect.

For more context, if that would be useful, I'm looking to create a reliable retry system that handles edge cases gracefully, so I'm experimenting with different approaches to break the connection and observe for any unexpected behaviour either on OS side, Python sockets or mctools since pretty much all other RCON clients don't handle edge cases like this properly.

If the `sock.recv` call always returns an empty byte or raises an exception when a peer terminates the connection or stops responding, that could be a simple fix. Otherwise another approach that comes to mind with setting the socket as non-blocking will probably require a lot of rewriting.

I have tested everything so far on Windows 10, Python 3.9 and Minecraft 1.16.5. Haven't tested on Linux yet, but I will report back if I find any inconsistencies related to this issue.

**Comment by Owen-Cochell** [comment]
Don't worry about being inexperienced with socket terminology. I am considerably less competent in this field than I thought, as I missed this very important socket behaviour. Programming in general can be very humbling sometimes, haha.

Anyway, I think auto-stopping the RCON client and raising an exception of some kind when the connection is dropped by the server is probably the best way to correct this. I agree with you, getting into non-blocking sockets and selectors would require a good amount of re-writing, and is probably unnecessary. I think this feature can be extended to the other clients as well, but I will do some more testing to see if they end socket connections like RCON does.

I do appreciate you taking the time to do some edge-case testing! Obviously, some things slipped through the cracks during development, this situation is a great example, so these tests are very helpful. If you find any more weird bugs or want some help with your testing, please don't hesitate to report them/ask. 

Again, i'll push out a fix over the coming days. I'll mark this as resolved once the hanging on our ends are corrected.

**Comment by Owen-Cochell** [comment]
Alright, I believe the issue is now resolved. 

Here is the new test code:

```python
# Simple test file for testing mctools features and bugs

from mctools.mclient import RCONClient
from mctools.errors import ProtoConnectionClosed  # We import the new ProtoConnectionClosed exception

with RCONClient('127.0.0.1', timeout=5.0) as rcon:

    # Login to the RCON server:

    rcon.login('password')

    # Just get some test data:

    print(rcon.command('list'))

    # Now, lets pause so we can kill the server:

    input("Pause for server kill...")

    try:

        # Run the same command again, should raise the 'ProtoConnectionClosed' exception:

        result = rcon.command('list')

    except ProtoConnectionClosed:  # Handling the new excpetion

        # Exception has been handled, client has been stopped:

        print("Connection status(Should be False): {}".format(rcon.proto.connected))
```

BaseProtocol, the class all client protocols inherit, will now raise 'ProtoConnectionClosed' when the remote socket is closed. This means all clients will have this behaviour, not just RCONClient. I tested this on my linux and windows machine, and the test code worked correctly.

I'll leave this issue open until you can confirm that mctools is behaving correctly. Let me know if anything is not working as expected!

**Comment by alexitx** [comment]
Tested the new code as well as my old example and everything seems to be working correctly now.
