### ISSUE TITLE
Fails to connect the socket after "Connection Refused" error raised

### ISSUE THREAD

**Issue by 3Diller** [Owen-Cochell/mctools#8]
I'm trying to write a code that starts Minecraft server and then trying to connect to the server multiple times. The problem is that after the first time RCONClient raises "ConnectionRefusedError" (due to Minecraft server being still starting) the client becomes unable to try to establish a connection since the client fails with `OSError: [Errno 22] Invalid argument`.

Minimal reproducible example:
```python
from time import sleep
from mctools import RCONClient

rcon = RCONClient('127.0.0.1', '12345')
for i in range(2):
    try:
        print('Attempt:', i)
        rcon.login('password')
    except ConnectionRefusedError:
        time.sleep(3)
    else:
        break
rcon.start()
rcon.command('say Hello World')
```
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/me/Projects/minebot/minebot/__main__.py", line 37, in <module>
    rcon.login('password')
  File "/Users/me/Projects/minebot/.venv/lib/python3.10/site-packages/mctools/mclient.py", line 377, in login
    pack = self.raw_send(self.proto.LOGIN, password)
  File "/Users/me/Projects/minebot/.venv/lib/python3.10/site-packages/mctools/mclient.py", line 295, in raw_send
    self.start()
  File "/Users/me/Projects/minebot/.venv/lib/python3.10/site-packages/mctools/mclient.py", line 204, in start
    self.proto.start()
  File "/Users/me/Projects/minebot/.venv/lib/python3.10/site-packages/mctools/protocol.py", line 187, in start
    self.sock.connect((self.host, self.port))
OSError: [Errno 22] Invalid argument
```

MacOS BigSur v11.6

**Comment by 3Diller** [comment]
As a workaround I can create a new RCONClient after each error - it works but still, I think it's not a proper behaviour.

**Comment by Owen-Cochell** [comment]
Hello! Thank you for pointing this out.

The main issue is the underlying socket object used by mctools does not support re-connection and other operations after the socket has been closed. In this case, the socket gets closed when the connection is refused, and any other operations on the same RCONClient will end up in failure. Creating a new RCONClient solves this problem by creating a new socket object, which is then able to connect and work as expected. This behavior is explained in the RCONClient documentation, but the explanation states that you can't re-use RCONClients after they have been stopped, and does not explain that clients can't be re-used after a network error. All in all, I think the issue is on mctools, as we do not explain the issue very well.

So, I think giving clients the ability to re-use themselves would be very helpful. This would allow users to attempt to connect multiple times, even after they have been stopped, or if a network error occurs. I think this would be very simple to implement, just create a new socket object after a failure or stop. This would solve your problem, and allow you to use the same client multiple times. I also this this can be explained better in the documentation as well.

I will be getting this fix out in a bit. Not sure exactly when as my schedule is very busy! Finally, thank you for pointing out this problem, it is really helpful.

Thanks!

**Comment by Owen-Cochell** [comment]
Alright, I have updated mctools that allows clients to start after they have been stopped. This means that clients can still be used if their are any connection issues, including the connection refused error you encountered. I have also updated the documentation to better explain this concept.

Here is some demo code that will attempt to connect to a server forever until a connection is made, all while using the same client:

```python
from time import sleep
from mctools import RCONClient

rcon = RCONClient('127.0.0.1', '12345')

num = 1

while True:

    try:

        print("Connection Attempt: {}".format(num))
        rcon.login('password')

        break

    except ConnectionRefusedError:

        print("Failed! Waiting 3 seconds ...")
        sleep(3)

    finally:

        num += 1

print("! Connection Scuessfull !")
rcon.command('say Hello RCON!')
```

The version  you want is `1.2.0`, and it is live up on PyPi. If this solves your problem, then we can close this issue! Otherwise, we can figure something else out. 

Thanks again!

**Comment by 3Diller** [comment]
Works like a charm! Thank you.
