### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Justuser3310** [Owen-Cochell/mctools#9]
After some time I get this error: `[Errno 32] Broken pipe`

Code:
https://hastebin.com/ozibayequf.py

**Comment by Owen-Cochell** [comment]
Hello, thanks for reporting this.

I am not sure that this is an issue with mctools. Are you in control of the target server? If not, then I suspect that the target server has some kind of rate limiting in place to stop all these repeated requests. The `[Errno 32] Broken pipe` occurs when the other side stops communicating with you, which is likely because you got blocked or rate limited. I would recommend implementing some rate limiting functionality in your code.

Otherwise, if this is your server, then I need to know more information about it. Are you hosting it yourself on a machine you own? Are you renting computing power for this server? How long does it take for the error to occur? If you do own the server, we can make sure that the firewall is 100% the problem. I would not recommend disabling or removing your firewall if this is the case, there are other ways to solve this problem.

Regardless, I think that this is a problem with a server/firewall that is blocking your application. Again, I would recommend implementing rate limiting in your application. For the sake of testing, I setup a bare-bones testing server with no firewall, and the script has been running for the past hour and a half. I don't think this is an issue with mctools, but I will leave this open in case I am mistaken or you could provide more info.

**Comment by Justuser3310** [comment]
`Are you in control of the target server?`
No.
`I would recommend implementing some rate limiting functionality in your code.`
Well... I will try it and reply, when I get results.

`If you do own the server, we can make sure that the firewall is 100% the problem.`
No firewall. I think this problem on server side. (But I can't be completely sure)

**Comment by Justuser3310** [comment]
Add to code `sleep(30)` every 30 seconds.
It works.

**Comment by Justuser3310** [comment]
Error... Again.
Now 5 types of error (No restart program):
```bash
[Errno 111] Connection refused
'sample'
'#FF9040'
index out of range
[Errno 32] Broken pipe
```

At the end "broken pipe" killed my program.

Code - https://gitlab.com/justuser31/minestatsping/-/blob/main/ping.py
Run with `nohup python3 ping.py &`

**Comment by Justuser3310** [comment]
P.S.: This error appeared after 1-2 days.

**Comment by Justuser3310** [comment]
And... disappeared... Strange
